=== Alexcr0103/LMSGI2023/DTD/Ejercicios Propios/prueba.dtd
<!ELEMENT Fruteria (frutas+,verduras*,procedencia?,hortalizas?)*>

<!ENTITY % datosComida    "nombre CDATA #REQUIRED
                           codigo ID #REQUIRED 
                           estado (bueno | malo | normal)  #IMPLIED
                           tipo NMTOKENS #REQUIRED
                            cultivo CDATA #IMPLIED">
<!ELEMENT frutas EMPTY>
 <!ATTLIST frutas %datosComida;>
 
<!ELEMENT verduras EMPTY>
 <!ATTLIST verduras %datosComida;
                        oferta NMTOKENS #FIXED "rebajas 50 por ciento">

<!ELEMENT hortalizas (bulbos|semillas)>
<!ELEMENT bulbos (#PCDATA)>
<!ELEMENT semillas EMPTY>

<!ELEMENT procedencia (#PCDATA | huerta | cooperativa| tienda)*>
  <!ELEMENT huerta (grande,pequeña?)>
  <!ELEMENT grande EMPTY>
  <!ATTLIST grande codigo IDREFS #REQUIRED>
  <!ELEMENT pequeña EMPTY>
  <!ATTLIST pequeña codigo IDREFS #REQUIRED>
  <!ELEMENT cooperativa (nacional+, (local |provincial))>
  <!ELEMENT nacional EMPTY>
  <!ATTLIST nacional codigo IDREFS #REQUIRED>
  <!ELEMENT local EMPTY>
  <!ELEMENT provincial EMPTY>

  <!ELEMENT tienda EMPTY>

=== Alexcr0103/LMSGI2023/DTD/Ejercicios Propios/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Fruteria SYSTEM "prueba.dtd">

<Fruteria>
    <frutas nombre="Fresa" codigo="F1" estado="bueno" tipo="generico d" cultivo="secano"/>
    <frutas nombre="Platano Canario" codigo="P1" estado="normal" tipo="nacional"/>
    <frutas nombre="Mango" codigo="M1" estado="bueno" tipo="exotico"/>
    <verduras nombre="Esparragos" codigo="E1" estado="bueno" tipo="generico"/>
    <verduras nombre="Habas" codigo="H1" estado="normal" tipo="generico" oferta="rebajas 50 por ciento"/>    
    <procedencia>Lugar de donde viene la comida
        <huerta>
            <grande codigo="F1" />
            <pequeÃ±a codigo="P1"/>
        </huerta>
        <cooperativa>
            <nacional codigo="E1"/>
            <local/>
        </cooperativa>
        <tienda/>
    </procedencia>
    <hortalizas>
        <bulbos>No hay existencias</bulbos>
    </hortalizas>
</Fruteria>
